project: 
  type: website
  output-dir: docs

website:
  title: "Hayley Hemme's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
 		- text: "Data Analysis Exercise"
            href: ./dataanalysis_exercise.html
    right:
      - icon: github 
        href: "https://github.com/hayhem/hayleyhemme-MADA-portfolio"       

format:
  html:
    theme: flatly
    highlight: zenburn
    css: styles.css
    toc: FALSE


